[package]
name = "EOS"
version = "0.1.0"
edition = "2024"

[workspace]
members = []
exclude = ["userspace"]

[dependencies]
limine = "0.6.5"
linked_list_allocator = "0.10"
miniz_oxide = { version = "0.7.4", default-features = false, features = ["with-alloc"] }
zune-jpeg = { version = "0.4.13", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false

[profile.release.package."*"]
opt-level = 3
