[package]
name = "user_app"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10", default-features = false }
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
regex-automata = { version = "0.4", default-features = false, features = ["alloc", "syntax", "meta", "unicode-perl"] }
zune-jpeg = { version = "0.4.13", default-features = false }
rust_h264 = "0.4"
rusttype = { version = "0.9.3", default-features = true }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
