[package]
name = "user_app"
version = "0.1.0"
edition = "2021"

[dependencies]
linked_list_allocator = "0.10"
miniz_oxide = { version = "0.7.4", default-features = false, features = ["with-alloc"] }
zune-jpeg = { version = "0.4.13", default-features = false }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
